const ALARM='weather-refresh-15m';
const CONDITION={0:['Clear sky','clear'],1:['Mainly clear','partly'],2:['Partly cloudy','partly'],3:['Overcast','cloud'],45:['Foggy','fog'],48:['Rime fog','fog'],51:['Drizzle','rain'],53:['Drizzle','rain'],55:['Heavy drizzle','rain'],61:['Slight rain','rain'],63:['Moderate rain','rain'],65:['Heavy rain','rain'],71:['Slight snow','snow'],73:['Snow','snow'],75:['Heavy snow','snow'],80:['Rain showers','rain'],81:['Rain showers','rain'],82:['Heavy showers','rain'],95:['Thunderstorm','storm'],96:['Thunderstorm','storm'],99:['Thunderstorm','storm']};
const iconPath=(kind,day)=>`assets/${day?kind:`night-${kind}`}.svg`;
function weatherFromText(text='',day=true){const s=String(text).toLowerCase();let k='clear';if(/thunder|storm/.test(s))k='storm';else if(/snow|sleet|ice/.test(s))k='snow';else if(/rain|shower|drizzle/.test(s))k='rain';else if(/fog|mist|haze/.test(s))k='fog';else if(/partly|mostly sunny|mostly clear/.test(s))k='partly';else if(/cloud|overcast/.test(s))k='cloud';return iconPath(k,day)}
function openCondition(code,day){const v=CONDITION[code]||CONDITION[0];return{label:v[0],icon:iconPath(v[1],day)}}
async function getJson(url,headers){const r=await fetch(url,{headers:headers||{}});if(!r.ok)throw Error(`${r.status}`);return r.json()}
async function getWeather(loc){if(loc.countryCode==='US'){try{return await getNwsWeather(loc)}catch(e){console.warn('NWS badge refresh failed',e)}}return getOpenWeather(loc)}
async function getNwsWeather(loc){const point=await getJson(`https://api.weather.gov/points/${loc.lat},${loc.lon}`,{Accept:'application/geo+json'}),p=point.properties;const h=await getJson(p.forecastHourly,{Accept:'application/geo+json'}),hours=(h.features||[]).map(x=>x.properties||{}),x=hours.find(v=>new Date(v.endTime||v.startTime).getTime()>=Date.now()-1800000)||hours[0];if(!x)throw Error('No NWS hourly data');const tempC=(Number(x.temperature)-32)*5/9;return{temp:Math.round(tempC),condition:x.shortForecast||'Weather',icon:weatherFromText(x.shortForecast,x.isDaytime!==false)}}
async function getOpenWeather(loc){const d=await getJson(`https://api.open-meteo.com/v1/forecast?latitude=${loc.lat}&longitude=${loc.lon}&current=temperature_2m,weather_code&hourly=is_day&temperature_unit=celsius&timezone=auto&forecast_days=1`),day=!!d.hourly?.is_day?.[0],v=CONDITION[d.current.weather_code]||CONDITION[0];return{temp:Math.round(d.current.temperature_2m),condition:v[0],icon:iconPath(v[1],day)}}
async function ensureOffscreen(){const contexts=await chrome.runtime.getContexts({contextTypes:['OFFSCREEN_DOCUMENT']});if(!contexts.length)await chrome.offscreen.createDocument({url:'offscreen.html',reasons:['BLOBS'],justification:'Render the current weather condition and temperature into the toolbar icon'});}
async function setToolbar(weather){await ensureOffscreen();const iconUrl=chrome.runtime.getURL(weather.icon);const response=await chrome.runtime.sendMessage({target:'offscreen',data:{temp:`${weather.temp}°`,condition:weather.condition,iconUrl}});if(response?.dataUrl)await chrome.action.setIcon({path:response.dataUrl});await chrome.action.setTitle({title:`${weather.condition} • ${weather.temp}°`});await chrome.action.setBadgeText({text:`${weather.temp}°`});await chrome.action.setBadgeBackgroundColor({color:'#17334a'});}
async function refresh(){const r=await chrome.storage.local.get(['defaultLocation']);const loc=r.defaultLocation;if(!loc?.lat||!loc?.lon)return;try{const weather=await getWeather(loc);await setToolbar(weather);await chrome.storage.local.set({weatherCache:{...weather,refreshedAt:new Date().toISOString()}})}catch(e){console.warn('Weather refresh failed',e)}}
async function ensureAlarm(){const alarm=await chrome.alarms.get(ALARM);if(!alarm)await chrome.alarms.create(ALARM,{delayInMinutes:15,periodInMinutes:15});}
chrome.runtime.onInstalled.addListener(()=>{ensureAlarm();refresh()});
chrome.runtime.onStartup.addListener(()=>{ensureAlarm();refresh()});
chrome.alarms.onAlarm.addListener(a=>{if(a.name===ALARM)refresh()});
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(message.type==='weather-refresh'){refresh();sendResponse({ok:true});return true}if(message.type==='set-weather-icon'){ensureOffscreen().then(()=>chrome.runtime.sendMessage({target:'offscreen',data:{temp:message.temp,condition:message.condition||'Weather',iconUrl:message.iconUrl}})).then(r=>r?.dataUrl?chrome.action.setIcon({path:r.dataUrl}):null).then(()=>sendResponse({ok:true})).catch(()=>sendResponse({ok:false}));return true}});
ensureAlarm();