const DEFAULT_SETTINGS={temperatureUnit:'celsius',windUnit:'kmh',theme:'dark'};
let settings={...DEFAULT_SETTINGS};let currentLocation=null;

document.addEventListener('DOMContentLoaded',()=>{
  loadSettings(()=>initLocation());
  document.getElementById('search-btn').addEventListener('click',searchLocation);
  document.getElementById('gps-btn').addEventListener('click',useGpsLocation);
  document.getElementById('settings-btn').addEventListener('click',toggleSettings);
  document.getElementById('close-settings').addEventListener('click',toggleSettings);
  document.getElementById('use-current-setting').addEventListener('click',useGpsLocation);
  document.getElementById('city-input').addEventListener('keypress',e=>{if(e.key==='Enter')searchLocation()});
  document.getElementById('temperature-setting').addEventListener('change',saveSettingsFromUI);
  document.getElementById('wind-setting').addEventListener('change',saveSettingsFromUI);
  document.getElementById('theme-setting').addEventListener('change',saveSettingsFromUI);
});
function loadSettings(done){chrome.storage.local.get(['weatherSettings'],r=>{settings={...DEFAULT_SETTINGS,...(r.weatherSettings||{})};applySettingsUI();done?.()})}
function applySettingsUI(){document.getElementById('temperature-setting').value=settings.temperatureUnit;document.getElementById('wind-setting').value=settings.windUnit;document.getElementById('theme-setting').value=settings.theme;document.body.classList.toggle('light-theme',settings.theme==='light')}
function saveSettingsFromUI(){settings={temperatureUnit:document.getElementById('temperature-setting').value,windUnit:document.getElementById('wind-setting').value,theme:document.getElementById('theme-setting').value};chrome.storage.local.set({weatherSettings:settings});applySettingsUI();document.getElementById('setting-status').textContent='Saved';if(currentLocation)loadLocationData(currentLocation.lat,currentLocation.lon,currentLocation.name,currentLocation.countryCode,false)}
function toggleSettings(){document.getElementById('settings-panel').classList.toggle('hidden')}
function initLocation(){chrome.storage.local.get(['defaultLocation'],r=>r.defaultLocation?loadLocationData(r.defaultLocation.lat,r.defaultLocation.lon,r.defaultLocation.name,r.defaultLocation.countryCode):useGpsLocation())}
function useGpsLocation(){chrome.storage.local.remove('defaultLocation');showLoader('Getting current location…');if(!navigator.geolocation){loadLocationData(40.7128,-74.006,'New York, US','US');return}navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude.toFixed(5),lon=p.coords.longitude.toFixed(5);const place=await reverseGeocode(lat,lon);loadLocationData(lat,lon,place.name,place.countryCode)},()=>loadLocationData(40.7128,-74.006,'New York, US','US'))}
async function reverseGeocode(lat,lon){try{const r=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${lat}&longitude=${lon}&localityLanguage=en`).then(x=>x.json());const city=r.city||r.locality||r.principalSubdivision||'Current location';const region=r.principalSubdivisionCode||r.principalSubdivision||'';const country=(r.countryCode||'').toUpperCase();return{name:[city,region&&region!==city?region:'',country&&country!=='US'?country:''].filter(Boolean).join(', '),countryCode:country}}catch(e){return{name:'Current location',countryCode:''}}}
async function searchLocation(){const q=document.getElementById('city-input').value.trim();if(!q)return;showLoader(`Searching “${q}”…`);try{const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=6&language=en&format=json`).then(x=>x.json());if(r.results?.length)renderSearchResults(r.results);else{alert('No matching locations found.');initLocation()}}catch(e){console.error(e);alert('Failed to search location.');initLocation()}}
function renderSearchResults(results){hideLoader();const box=document.getElementById('search-results-list');box.className='search-results-container';box.innerHTML='<b>Select a location</b>';results.forEach(loc=>{const state=[loc.admin1,loc.country_code?.toUpperCase()].filter(Boolean).join(', '),b=document.createElement('button');b.className='search-result-item';b.textContent=`${loc.name}${state?` (${state})`:''}`;b.onclick=()=>{const lat=loc.latitude.toFixed(5),lon=loc.longitude.toFixed(5),country=(loc.country_code||'').toUpperCase();chrome.storage.local.set({defaultLocation:{lat,lon,name:b.textContent,countryCode:country}});box.className='hidden';document.getElementById('city-input').value='';loadLocationData(lat,lon,b.textContent,country)};box.appendChild(b)})}
async function loadLocationData(lat,lon,name,countryCode,show=true){if(show)showLoader('Loading weather…');currentLocation={lat,lon,name,countryCode};try{let point=null;const isUS=countryCode==='US';if(isUS){try{point=await fetchNwsPoint(lat,lon)}catch(e){console.warn('NWS unavailable, using Open-Meteo',e)}}if(point){await renderNwsWeather(point,lat,lon,name)}else{const d=await fetchOpenMeteo(lat,lon);renderOpenMeteoWeather(d,name)}hideLoader()}catch(e){console.error(e);showLoader(`Unable to fetch weather data: ${e.message||e}`)}}
async function fetchNwsPoint(lat,lon){const r=await fetch(`https://api.weather.gov/points/${lat},${lon}`,{headers:{Accept:'application/geo+json'}});if(!r.ok)throw new Error(`NWS points ${r.status}`);return r.json()}
async function fetchNws(url){const r=await fetch(url,{headers:{Accept:'application/geo+json'}});if(!r.ok)throw new Error(`NWS ${r.status}`);return r.json()}
async function renderNwsWeather(point,lat,lon,name){const p=point.properties||{};const [forecast,hourly,stationList]=await Promise.all([fetchNws(p.forecast),fetchNws(p.forecastHourly),fetchNws(p.observationStations)]);const periods=(forecast.features||[]).map(x=>x.properties||{});const hp=(hourly.features||[]).map(x=>x.properties||{});let observation=null;for(const s of(stationList.features||[]).slice(0,3)){try{const o=await fetchNws(`https://api.weather.gov/stations/${s.properties.stationIdentifier}/observations/latest`);if(o?.properties){observation=o.properties;break}}catch(e){}}
  const current=normalizeNwsCurrent(observation||{},hp[0]);const tempC=current.tempC??(hp[0]?.temperature!=null?fToC(hp[0].temperature):fToC(periods[0]?.temperature??0));
  const range=nwsTodayHighLow(hp,tempC);const day=periods.find(x=>x.isDaytime)||periods[0];const di=day?periods.indexOf(day):0;const night=di>=0?periods[di+1]:null;const highC=range.highC??(day?.temperature!=null?fToC(day.temperature):tempC);const lowC=range.lowC??(night?.temperature!=null?fToC(night.temperature):tempC);
  renderCommon(name,tempC,highC,lowC,current.forecast||day?.shortForecast||'—',day?.detailedForecast||current.forecast||'Detailed forecast unavailable.',current);
  set('forecast-source','NWS');set('hourly-source','NWS');set('data-source','NWS');set('uv-index','--');set('precip-total','--');set('precip-prob',`${Math.round(day?.probabilityOfPrecipitation?.value||0)}%`);set('last-refresh',`NWS • ${time(new Date().toISOString())}`);
  renderNwsHourly(hp);renderNwsDaily(periods);await renderAstronomy(lat,lon);updateExtensionIcon(round(convertTemp(tempC)),weatherIcon(day?.shortForecast,current.forecast));
}
function renderCommon(name,tempC,highC,lowC,forecast,description,current){set('location-name',name);set('updated-at',`Updated ${time(current.time)}`);set('current-temp',round(convertTemp(tempC)));setUnit();set('short-forecast',forecast);set('today-high',`${round(convertTemp(highC))}°`);set('today-low',`${round(convertTemp(lowC))}°`);set('condition-description',description);set('feels-like',`${round(convertTemp(current.feelsC??tempC))}°${tempSymbol()}`);set('humidity',current.humidity==null?'--%':`${Math.round(current.humidity)}%`);set('pressure',current.pressure==null?'-- hPa':`${Math.round(current.pressure)} hPa`);set('wind',`${formatWind(current.windKmh)} ${windSymbol()} ${current.windDir||'--'}`);set('cloud-cover',current.cloud==null?'--%':`${Math.round(current.cloud)}%`);set('visibility',formatVisibility(current.visibilityKm));document.getElementById('wind-arrow').style.transform=`rotate(${degFromText(current.windDir)}deg)`;set('today-date',date(current.time))}
function nwsTodayHighLow(h,tempC){const temps=h.slice(0,24).map(x=>Number(x.temperature)).filter(Number.isFinite).map(fToC);if(temps.length>=2)return{highC:Math.max(tempC,...temps),lowC:Math.min(tempC,...temps)};return{highC:null,lowC:null}}
function normalizeNwsCurrent(o,h){const val=(k,f=null)=>o?.[k]?.value??f;const tempC=val('temperature',null);const wc=val('windChill',null);const hi=val('heatIndex',null);const p=val('barometricPressure',null);const vis=val('visibility',null);const ws=val('windSpeed',null);return{time:o?.timestamp||h?.startTime||new Date().toISOString(),tempC,feelsC:wc??hi??tempC,humidity:val('relativeHumidity',h?.relativeHumidity?.value),pressure:p==null?null:p/100,visibilityKm:vis==null?null:vis/1000,windKmh:ws==null?parseSpeedKmh(h?.windSpeed):ws*3.6,windDir:o?.windDirection?.value??h?.windDirection,cloud:cloudFromLayers(o?.cloudLayers||[]),forecast:o?.textDescription||h?.shortForecast}}
function parseSpeedKmh(v){const n=parseFloat(String(v??''));return Number.isFinite(n)?n*1.609344:0}
function cloudFromLayers(a){if(!a?.length)return null;const max={SKC:0,CLR:0,FEW:25,SCT:50,BKN:75,OVC:100};return Math.max(...a.map(x=>max[x.amount]??50))}
function renderNwsHourly(h){const box=document.getElementById('hourly-forecast');box.innerHTML='';h.slice(0,6).forEach((x,i)=>{const e=document.createElement('div');e.className='hourly-item'+(i===0?' now':'');e.innerHTML=`<span class="hourly-time">${i?' '+new Date(x.startTime).toLocaleTimeString([],{hour:'numeric'}):'Now'}</span><img class="hourly-icon" src="${weatherIcon(x.shortForecast)}" alt=""><b>${round(convertTemp(fToC(x.temperature)))}°</b><small>☔ ${Math.round(x.probabilityOfPrecipitation?.value||0)}%</small>`;box.appendChild(e)})}
function renderNwsDaily(p){const box=document.getElementById('daily-forecast');box.innerHTML='';let n=0;for(let i=0;i<p.length&&n<7;i++){const x=p[i];if(!x.isDaytime)continue;const night=p[i+1];const high=x.temperature!=null?fToC(x.temperature):null;const low=night?.temperature!=null?fToC(night.temperature):high;const e=document.createElement('div');e.className='daily-row';e.innerHTML=`<b>${n?' '+new Date(x.startTime).toLocaleDateString([],{weekday:'short'}):'Today'}</b><img src="${weatherIcon(x.shortForecast)}" alt=""><span>${escapeHtml(x.shortForecast||'—')}</span><strong>${round(convertTemp(low))}° / ${round(convertTemp(high))}°</strong><em>${Math.round(x.probabilityOfPrecipitation?.value||0)}%</em>`;box.appendChild(e);n++}}
async function renderAstronomy(lat,lon){try{const d=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&daily=sunrise,sunset,moonrise,moonset&timezone=auto&forecast_days=1`).then(r=>r.json());const x=d.daily;set('sunrise',time(x.sunrise?.[0]));set('sunset',time(x.sunset?.[0]));set('moonrise',time(x.moonrise?.[0]));set('moonset',time(x.moonset?.[0]))}catch(e){set('sunrise','--:--');set('sunset','--:--');set('moonrise','--:--');set('moonset','--:--')}}
async function fetchOpenMeteo(lat,lon){const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,cloud_cover,pressure_msl,wind_speed_10m,wind_direction_10m&hourly=temperature_2m,precipitation_probability,uv_index,weather_code,visibility&daily=weather_code,temperature_2m_max,temperature_2m_min,uv_index_max,sunrise,sunset,moonrise,moonset,precipitation_sum,precipitation_probability_max&temperature_unit=celsius&wind_speed_unit=kmh&timezone=auto&forecast_days=7`;const r=await fetch(u);if(!r.ok)throw new Error(`Open-Meteo ${r.status}`);return r.json()}
function renderOpenMeteoWeather(d,name){const c=d.current,x=d.daily,w=getWeatherCondition(c.weather_code);renderCommon(name,c.temperature_2m,x.temperature_2m_max[0],x.temperature_2m_min[0],w.label,openMeteoDescription(c.weather_code,x.weather_code?.[0],x.precipitation_probability_max?.[0],x.precipitation_sum?.[0]),{time:c.time,feelsC:c.apparent_temperature,humidity:c.relative_humidity_2m,pressure:c.pressure_msl,visibilityKm:(d.hourly.visibility?.[0]||0)/1000,windKmh:c.wind_speed_10m,windDir:dir(c.wind_direction_10m),cloud:c.cloud_cover});set('forecast-source','Open-Meteo');set('hourly-source','Open-Meteo');set('data-source','Open-Meteo');set('uv-index',x.uv_index_max[0]?.toFixed(1)||'--');set('precip-total',`${x.precipitation_sum[0]?.toFixed(1)||'0.0'} mm`);set('precip-prob',`${x.precipitation_probability_max[0]||0}%`);set('sunrise',time(x.sunrise[0]));set('sunset',time(x.sunset[0]));set('moonrise',time(x.moonrise[0]));set('moonset',time(x.moonset[0]));renderHourly(d.hourly);renderDaily(x);set('last-refresh',`Open-Meteo • ${time(new Date().toISOString())}`);updateExtensionIcon(round(convertTemp(c.temperature_2m)),w.icon)}
function renderHourly(h){const box=document.getElementById('hourly-forecast');box.innerHTML='';const now=Date.now();let n=0;for(let i=0;i<h.time.length&&n<6;i++){const t=new Date(h.time[i]);if(t.getTime()<now-3600000)continue;const w=getWeatherCondition(h.weather_code[i]),e=document.createElement('div');e.className='hourly-item'+(n===0?' now':'');e.innerHTML=`<span class="hourly-time">${n?' '+t.toLocaleTimeString([],{hour:'numeric'}):'Now'}</span><img class="hourly-icon" src="${w.icon}" alt=""><b>${round(convertTemp(h.temperature_2m[i]))}°</b><small>☔ ${Math.round(h.precipitation_probability[i]||0)}%</small>`;box.appendChild(e);n++}}
function renderDaily(d){const box=document.getElementById('daily-forecast');box.innerHTML='';d.time.forEach((day,i)=>{const w=getWeatherCondition(d.weather_code[i]),e=document.createElement('div');e.className='daily-row';e.innerHTML=`<b>${i?' '+new Date(day+'T12:00:00').toLocaleDateString([],{weekday:'short'}):'Today'}</b><img src="${w.icon}" alt=""><span>${escapeHtml(w.label)}</span><strong>${round(convertTemp(d.temperature_2m_min[i]))}° / ${round(convertTemp(d.temperature_2m_max[i]))}°</strong><em>${Math.round(d.precipitation_probability_max[i]||0)}%</em>`;box.appendChild(e)})}
function getWeatherCondition(c){const m={0:['Clear sky','clear.svg'],1:['Mainly clear','partly.svg'],2:['Partly cloudy','partly.svg'],3:['Overcast','cloud.svg'],45:['Foggy','fog.svg'],48:['Rime fog','fog.svg'],51:['Drizzle','rain.svg'],53:['Drizzle','rain.svg'],55:['Heavy drizzle','rain.svg'],61:['Slight rain','rain.svg'],63:['Moderate rain','rain.svg'],65:['Heavy rain','rain.svg'],71:['Slight snow','snow.svg'],73:['Snow','snow.svg'],75:['Heavy snow','snow.svg'],80:['Rain showers','rain.svg'],81:['Rain showers','rain.svg'],82:['Heavy showers','rain.svg'],95:['Thunderstorm','storm.svg'],96:['Thunderstorm','storm.svg'],99:['Thunderstorm','storm.svg']};const v=m[c]||m[0];return{label:v[0],icon:`assets/${v[1]}`}}
function weatherIcon(text=''){const s=String(text).toLowerCase();if(/thunder|storm/.test(s))return'assets/storm.svg';if(/snow|sleet|ice/.test(s))return'assets/snow.svg';if(/rain|shower|drizzle/.test(s))return'assets/rain.svg';if(/fog|mist|haze/.test(s))return'assets/fog.svg';if(/partly|mostly sunny|mostly clear/.test(s))return'assets/partly.svg';if(/cloud|overcast/.test(s))return'assets/cloud.svg';return'assets/clear.svg'}
function openMeteoDescription(current,daily,pop,precip){const w=getWeatherCondition(current??daily);let s=w.label;if(pop>0)s+=` with a ${Math.round(pop)}% precipitation chance`;if(precip>0)s+=` and about ${Number(precip).toFixed(1)} mm of precipitation today`;return s+'.'}
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v}function setUnit(){set('temp-unit',tempSymbol())}function tempSymbol(){return settings.temperatureUnit==='fahrenheit'?'°F':'°C'}function windSymbol(){return settings.windUnit==='mph'?'mph':'km/h'}function convertTemp(c){return settings.temperatureUnit==='fahrenheit'?(c*9/5)+32:c}function fToC(f){return(f-32)*5/9}function formatWind(kmh){return Math.round(settings.windUnit==='mph'?kmh/1.609344:kmh)}function formatVisibility(km){return km==null?'-- km':`${Number(km).toFixed(1)} km`}function round(v){return Number.isFinite(Number(v))?Math.round(Number(v)):'--'}function time(v){return v?new Date(v).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'--:--'}function date(v){return new Date(v).toLocaleDateString([],{month:'short',day:'numeric'})}function dir(d){return['N','NE','E','SE','S','SW','W','NW'][Math.round((d||0)/45)%8]}function degFromText(d){if(typeof d==='number')return d;const m={N:0,NE:45,E:90,ESE:112.5,SE:135,SSE:157.5,S:180,SSW:202.5,SW:225,WSW:247.5,W:270,WNW:292.5,NW:315,NNW:337.5};return m[d]??0}function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function showLoader(m){document.getElementById('loader').querySelector('span:last-child').textContent=m;document.getElementById('loader').classList.remove('hidden');document.getElementById('content').classList.add('hidden')}function hideLoader(){document.getElementById('loader').classList.add('hidden');document.getElementById('content').classList.remove('hidden')}
async function updateExtensionIcon(temp,iconUrl){try{const c=await chrome.runtime.getContexts({contextTypes:['OFFSCREEN_DOCUMENT']});if(!c.length)await chrome.offscreen.createDocument({url:'offscreen.html',reasons:['BLOBS'],justification:'Render canvas icon for extension badge'});chrome.runtime.sendMessage({target:'offscreen',data:{temp:`${temp}°`,iconUrl}},r=>{if(!chrome.runtime.lastError&&r?.dataUrl)chrome.action.setIcon({path:r.dataUrl})})}catch(e){console.warn(e)}}